apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-svc
  name: {{ .Release.Name }}-svc
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: {{ .Values.service.nodePort.http }}
  selector:
    app: {{ .Release.Name }}-deployment
  type: NodePort